### ISSUE TITLE
Low performance on RX 7900 XTX

### ISSUE THREAD

**Issue by evshiron** [ROCm/triton#250]
I compiled Triton using [this commit](https://github.com/ROCmSoftwarePlatform/triton/commit/36f7c9872a72e4ed9bc1a73a6a46b0188363577f) and ran the tutorial on matrix multiplication from:

* https://triton-lang.org/main/getting-started/tutorials/03-matrix-multiplication.html

Here are the results:

```
triton_output=tensor([[-30.4844,   7.5391, -11.2500,  ..., -16.4531,  -5.3398,   3.8965],
        [ 52.5938, -11.8125, -29.0312,  ..., -32.6250, -23.9531, -27.7812],
        [ 22.6562, -21.3438,   1.1143,  ...,  -2.9609, -78.3750,  34.2812],
        ...,
        [-13.5234,  27.5469,  -8.5234,  ...,  -6.9727,   9.0781,  18.9219],
        [  1.8652,   9.3516,   6.7500,  ..., -16.6250, -21.3125, -19.4531],
        [-17.5938, -28.5938,   0.5933,  ...,  22.0000,  -3.4648,  43.1250]],
       device='cuda:0', dtype=torch.float16)
torch_output=tensor([[-30.4844,   7.5391, -11.2500,  ..., -16.4531,  -5.3398,   3.8965],
        [ 52.5938, -11.8125, -29.0312,  ..., -32.6250, -23.9531, -27.7812],
        [ 22.6562, -21.3438,   1.1143,  ...,  -2.9609, -78.3750,  34.2812],
        ...,
        [-13.5234,  27.5469,  -8.5234,  ...,  -6.9727,   9.0781,  18.9219],
        [  1.8652,   9.3516,   6.7500,  ..., -16.6250, -21.3125, -19.4531],
        [-17.5938, -28.5938,   0.5933,  ...,  22.0000,  -3.4648,  43.1250]],
       device='cuda:0', dtype=torch.float16)
❌ Triton and Torch differ
matmul-performance:
         M      cuBLAS     Triton
0    256.0    3.554118   1.183035
1    384.0   10.523762   2.623566
2    512.0   19.199332   4.479374
3    640.0   29.319314   5.645366
4    768.0   38.318727   7.242311
5    896.0   47.505159   8.043466
6   1024.0   40.605899  10.228889
7   1152.0   64.283564  10.787979
8   1280.0   54.521752  11.153255
9   1408.0   67.415601  10.666534
10  1536.0   72.965715  10.011295
11  1664.0   76.451147  11.735046
12  1792.0   73.075487  12.004438
13  1920.0   85.000276  12.583125
14  2048.0   84.205962  12.684253
15  2176.0   86.835994  12.447690
16  2304.0   99.782090  12.922991
17  2432.0  100.501941  12.648365
18  2560.0   97.850012  13.088321
19  2688.0   97.527506  13.020227
20  2816.0   98.249215  13.060892
21  2944.0   99.382067  13.087734
22  3072.0   97.037371  13.386896
23  3200.0   97.857284  13.124832
24  3328.0   98.378948  13.196211
25  3456.0   98.952172  13.240287
26  3584.0   99.489725  13.365592
27  3712.0  100.513236  13.270990
28  3840.0  101.268567  13.364793
29  3968.0   99.382410  13.320902
30  4096.0  102.281068  13.527350
```

Firstly, this "differ" could be a false positive, but the performance of Triton only reaches 13% of rocBLAS.

I am afraid there will be a lot of optimizations to be done?

**Comment by stephen-youn** [comment]
i observed a similar large perf degradation with mi200 and have the same question when can we expect the fix/optimization come?

![image](https://github.com/ROCmSoftwarePlatform/triton/assets/13525892/7a9c00e7-3178-41d7-ac70-66614bade877)

**Comment by binarman** [comment]
@evshiron  @stephen-youn 
hi!
Recent PR https://github.com/ROCmSoftwarePlatform/triton/pull/265 should mitigate this issue on MI100/MI200,
And we working on further optimizations.

@evshiron what hardware do you use?
Currently we are focusing on server hardware (MI series wih MFMA instructions support). Unfortunately, low performance is expected on consumer grade hardware.

**Comment by evshiron** [comment]
Thank you for your response. I am currently using RX 7900 XTX and I am aware of the state of consumer-grade GPUs. I will continue to pay attention to updates on this matter.

**Comment by wsippel** [comment]
> @evshiron what hardware do you use? Currently we are focusing on server hardware (MI series wih MFMA instructions support). Unfortunately, low performance is expected on consumer grade hardware.

I don't mean to be confrontational, but didn't Dr. Lisa Su recently promise AMD would make sure AI on high-end consumer cards, the 7900 series in particular, would be a focus going forward? I get that PR is a thing, and that the datacenter products are obviously most important, but "low performance is expected" really doesn't cut it in light of her statement. Also, it seems AMD often forgets the WX line of products exists. Those are expensive, supposedly professional cards, and with solid four digit price tags, should get first-class ROCm support.

**Comment by stephen-youn** [comment]
> @evshiron @stephen-youn hi! Recent PR #265 should mitigate this issue on MI100/MI200, And we working on further optimizations.
> 
> @evshiron what hardware do you use? Currently we are focusing on server hardware (MI series wih MFMA instructions support). Unfortunately, low performance is expected on consumer grade hardware.

the tflops in #265 seems better but still only half of the tflops when compared with cuBLAS, so are we expecting it to be at least compatible with culblass gemm?

**Comment by binarman** [comment]
@wsippel 
Good day!

Sorry for confusion, "low performance is expected" is related to the current state of the project, not about future plans.
Unfortunately, I can not answer any big questions about global planning, because I am not responsible for this.

AMD has a variety of projects dedicated to machine learning besides Triton, maybe they will be more suitable for your tasks and hardware.
For example, if you are primary interested in GEMM, see [rocBLAS](https://github.com/ROCmSoftwarePlatform/rocBLAS). If you need convolutions, RNNS, etc.: [MIOpen](https://github.com/ROCmSoftwarePlatform/MIOpen)

**Comment by binarman** [comment]
@stephen-youn 

>the tflops in https://github.com/ROCmSoftwarePlatform/triton/pull/265 seems better but still only half of the tflops when compared with cuBLAS, so are we expecting it to be at least compatible with culblass gemm?

I can not tell you when triton will be in parity with `cuBLAS`(actually, I believe this tutorial actually use `rocBLAS`, `cuBLAS` is a wrong string which we copied from upstream repo), but we are working on this at the moment, have some ideas how to optimize it, so at least some improvements are expected soon.

**Comment by alefimov-amd** [comment]
+cc @joviliast

I can not add you as an assignee at the moment, sorry :slightly_frowning_face:

**Comment by joviliast** [comment]
> +cc @joviliast
> 
> I can not add you as an assignee at the moment, sorry 🙁

Ok, let's wait for access. Anyway, I started working on it.

**Comment by joviliast** [comment]
I measured perf on https://github.com/ROCm/triton/pull/481 . Results looks not bad.
Device RX 7900 XT. Please check.
[matmul-performance-tflops.txt](https://github.com/ROCm/triton/files/14113731/matmul-performance-tflops.txt)

**Comment by zhanglx13** [comment]
@evshiron Now the Navi support is upstreamed into https://github.com/openai/triton. Please open tickets there if you find any issues.
