### ISSUE TITLE
WMMA instructions are not supported for GEMM

### ISSUE THREAD

**Issue by joviliast** [ROCm/triton#448]
Here is highlevel tasks for WMMA enabling for GEMM:

- [x] Implement BlockedToWMMA in TritonAMDGPUAccelerateMatmulPass according to required layout (https://github.com/ROCmSoftwarePlatform/triton/pull/423)
- [x] Support WMMA in ConvertTritonGPUToLLVMPass:
  - [x] Implement conversion from WMMA layout
  - [x] Implement SharedToDotOperandWMMA
  - [x] Implement packMfmaOperand for ElementwiseOpToLLVM
- [x] Support WMMA in TritonGPURemoveLayoutConversionsPass
- [x] Fix bugs and pitfalls
  - [x] Fix Flash attention kernel
  - [x] Fix swizzling (wip)

This issue includes https://github.com/ROCmSoftwarePlatform/triton/issues/250.

**Comment by xiaohuguo2023** [comment]
❌ Triton and Torch differ abserved in[ ](https://github.com/ROCmSoftwarePlatform/triton/issues/250.)

can also be reproduced in A100 and V100.

**Comment by joviliast** [comment]
WMMA is partially enabled in draft PR:
https://github.com/ROCmSoftwarePlatform/triton/pull/481

**Comment by joviliast** [comment]
Performance results on working branch using  WMMA instructions:

[matmul-performance-tflops.txt](https://github.com/ROCm/triton/files/14125270/matmul-performance-tflops.txt)

Unfortunately, didn't wait for results without WMMA to compare.
[fused-attention-tflops.txt](https://github.com/ROCm/triton/files/14125269/fused-attention-tflops.txt)

**Comment by joviliast** [comment]
fused-attention mismatches for now

**Comment by joviliast** [comment]
All the works are moved to the upstream for now. Please check PRs:

https://github.com/openai/triton/pull/3112 Introduce WMMA layout attr
https://github.com/openai/triton/pull/3170 Emit Indices for WMMA
https://github.com/openai/triton/pull/3171 Support SharedToDotOperandWMMA
https://github.com/openai/triton/pull/3199 Convert WMMA dot op to LLVM

**Comment by joviliast** [comment]
> fused-attention mismatches for now


Fused attention is fixed here https://github.com/joviliast/triton/tree/wmma-convertions

**Comment by joviliast** [comment]
All required PRs were merged to the upstream: https://github.com/openai/triton
Swizzling is not working for now. Fix in progress,
