### ISSUE TITLE
cannot import name 'cdiv' from 'triton' (unknown location)

### ISSUE THREAD

**Issue by ehartford** [ROCm/triton#489]
I am getting this error cannot import name 'cdiv' from 'triton'

**Comment by zhanglx13** [comment]
@ehartford Can you provide more information about the environment? Like 
- GPU
- container if you are using docker
- pytorch version
- triton version (which commit)

**Comment by ehartford** [comment]
I was unblocked, by using openai/triton instead of ROCmSoftwarePlatform/triton

gpu is mi210
pytorch is nightly
no container
ROCmSoftwarePlatform/triton is main/latest compiled from source
