### ISSUE TITLE
[Issue]: Unified memory tensors aren't seen as accessible to Triton

### ISSUE THREAD

**Issue by joerowell** [ROCm/triton#516]
### Problem Description

I have some code that returns a Pytorch tensor from C++ that's backed by unified memory (e.g via `hipMallocManaged`). On CUDA platforms, I can pass the resulting pointer directly to Triton and the compiler doesn't complain. On the other hand, I get this error on HIP-based systems:

```
Pointer argument (at 0) cannot be accessed from Triton (cpu tensor?)
```

It looks like this is because of the following returns `Device pointer!` on CUDA platforms:

```c++
#include<cuda.h>
#include<cuda_runtime_api.h>
#include<iostream>
#include<cstdint>

int main(int argc, char** argv) {
        int *ptr;
        auto err = cudaMallocManaged(&ptr, sizeof(int)*100, cudaMemAttachGlobal);
        if (err != cudaSuccess) {
                std::cerr << "Err: could not malloc in unified memory!" << std::endl;
        }

        uint64_t dev_ptr;
        int status = cuPointerGetAttribute(&dev_ptr, CU_POINTER_ATTRIBUTE_DEVICE_POINTER, (uint64_t)ptr);
        if (status == CUDA_ERROR_INVALID_VALUE) {
                std::cerr << "Err: not device pointer!" << std::endl;
        } else {
                std::cerr << "Device pointer!" << std::endl;
        }

        cudaFree(ptr);
}

```

I can't test it at the moment, but my gut feeling is that the same is not true for HIP?

### Operating System

Ubuntu 22.04

### CPU

-

### GPU

AMD Instinct MI300X

### ROCm Version

ROCm 6.0.0

**Comment by zhanglx13** [comment]
@jataylo Do you know who might have experience with this issue?

**Comment by joerowell** [comment]
I've investigated this further.

The issue is that the ROCM version of Triton uses the `libamdhip64.so` that comes with the system-wide installation of ROCM. However, `pytorch-rocm` _also_ ships with its own version of `libamdhip64.so` that is used by Pytorch. This means that there's two separate runtimes that are initialised, and thus there's actually very little guarantee that memory allocated in one runtime can be used in the other.

**Comment by jerryyin** [comment]
This already fixed by upstream triton. Let us know if you still bump into this.
