### ISSUE TITLE
[Feature]: Mark dev version as such

### ISSUE THREAD

**Issue by fxmarty** [ROCm/triton#577]
### Suggestion Description

Hi,

the `triton-mlir` branch is marked as `2.1.0`: https://github.com/ROCm/triton/blob/229557261fd95c52c1b5c8f473128b542af453f7/python/triton/__init__.py#L2

I think it would be useful to change this to reflect that `triton-mlir` is a dev branch.

Thank you

**Comment by jerryyin** [comment]
@fxmarty This is to let you know that `triton-mlir` branch is deprecated and we have moved to upstream.

**Comment by fxmarty** [comment]
@jerryyin great!
